# init numpy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [3]:
python_list = [[1, 1, 1], [2, 2, 2]]
python_list

[[1, 1, 1], [2, 2, 2]]

In [4]:
np_list = np.array([[1, 1, 1], [2, 2, 2]])
np_list

array([[1, 1, 1],
       [2, 2, 2]])

In [5]:
# broadcasting
arr1 = np.array([1, 1, 1])
arr2 = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])

print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 - arr2)
print(arr1 / arr2)

[[11 11 11]
 [21 21 21]
 [31 31 31]]
[[10 10 10]
 [20 20 20]
 [30 30 30]]
[[ -9  -9  -9]
 [-19 -19 -19]
 [-29 -29 -29]]
[[0.1        0.1        0.1       ]
 [0.05       0.05       0.05      ]
 [0.03333333 0.03333333 0.03333333]]


In [6]:
print(arr2)
arr2.shape

[[10 10 10]
 [20 20 20]
 [30 30 30]]


(3, 3)

# index & slice

In [7]:
ndarr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
ndarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
print(ndarr[2][1])
print(ndarr[2, 1])

6
6


In [9]:
print(ndarr[2:, 0])
print(ndarr[:, 1])

[5 7]
[2 4 6 8]


In [10]:
print(ndarr[0:3:2])
print(ndarr[0:3:2, 1])

[[1 2]
 [5 6]]
[2 6]


# gen ndarray

In [11]:
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [14]:
np.arange(1, 5, 2)

array([1, 3])

In [15]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [16]:
np.linspace(0, 30, 10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
arr = np.arange(0, 5)
arr_copy = arr.copy()
print(arr)
print(arr_copy)

[0 1 2 3 4]
[0 1 2 3 4]


In [19]:
arr_ref = arr
arr_ref[:] = 100
print(arr)
print(arr_ref)
print(arr_copy)

[100 100 100 100 100]
[100 100 100 100 100]
[0 1 2 3 4]


In [20]:
def print_id(n):
    print(id(n))

# The function is passed an address.
a = 'ref'
print(id(a))
print_id(a)

140008442668336
140008442668336


In [21]:
print_id(arr)
print_id(arr_ref)
print_id(arr_copy)

140008115884800
140008115884800
140008115885040


In [22]:
shape = (2, 4, 3)
zeros = np.zeros(shape)
print(zeros)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [24]:
ones = np.ones(shape)
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [31]:
print(np.random.rand())
print(np.random.rand(3))
print(np.random.rand(2, 3))

0.5391217252382466
[0.46768084 0.20803955 0.25481497]
[[0.68903954 0.13575966 0.08074192]
 [0.15496891 0.84002299 0.87162761]]


In [33]:
print(np.random.randn())
print(np.random.randn(2, 3))

-0.19628039181463722
[[ 1.17634775  0.50359663  0.07587237]
 [-0.03457844  1.92859073 -1.70589773]]


In [36]:
np.random.randint(3, 7, size=(2, 3))

array([[4, 3, 6],
       [5, 6, 5]])

In [35]:
np.random.randint(2, 10, (2, 5))

array([[2, 3, 8, 8, 7],
       [6, 6, 3, 2, 7]])

In [38]:
np.random.randint(2, 10)

7

In [41]:
np.random.randint(1, 100, (5, 2)).reshape(2, 5)

array([[45, 74, 74, 49,  1],
       [86, 60, 75,  4, 50]])

In [47]:
arr = np.arange(0, 12)
print(arr)
print(arr.reshape(3, 4))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# function