# init numpy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [3]:
python_list = [[1, 1, 1], [2, 2, 2]]
python_list

[[1, 1, 1], [2, 2, 2]]

In [4]:
np_list = np.array([[1, 1, 1], [2, 2, 2]])
np_list

array([[1, 1, 1],
       [2, 2, 2]])

In [5]:
# broadcasting
arr1 = np.array([1, 1, 1])
arr2 = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])

print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 - arr2)
print(arr1 / arr2)

[[11 11 11]
 [21 21 21]
 [31 31 31]]
[[10 10 10]
 [20 20 20]
 [30 30 30]]
[[ -9  -9  -9]
 [-19 -19 -19]
 [-29 -29 -29]]
[[0.1        0.1        0.1       ]
 [0.05       0.05       0.05      ]
 [0.03333333 0.03333333 0.03333333]]


In [6]:
print(arr2)
arr2.shape

[[10 10 10]
 [20 20 20]
 [30 30 30]]


(3, 3)

# index & slice

In [7]:
ndarr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
ndarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
print(ndarr[2][1])
print(ndarr[2, 1])

6
6


In [9]:
print(ndarr[2:, 0])
print(ndarr[:, 1])

[5 7]
[2 4 6 8]


In [10]:
print(ndarr[0:3:2])
print(ndarr[0:3:2, 1])

[[1 2]
 [5 6]]
[2 6]


# gen ndarray

In [11]:
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [14]:
np.arange(1, 5, 2)

array([1, 3])

In [15]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [16]:
np.linspace(0, 30, 10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
arr = np.arange(0, 5)
arr_copy = arr.copy()
print(arr)
print(arr_copy)

[0 1 2 3 4]
[0 1 2 3 4]


In [19]:
arr_ref = arr
arr_ref[:] = 100
print(arr)
print(arr_ref)
print(arr_copy)

[100 100 100 100 100]
[100 100 100 100 100]
[0 1 2 3 4]


In [20]:
def print_id(n):
    print(id(n))

# The function is passed an address.
a = 'ref'
print(id(a))
print_id(a)

140052945130800
140052945130800


In [21]:
print_id(arr)
print_id(arr_ref)
print_id(arr_copy)

140052484112432
140052484112432
140052484529168


In [22]:
shape = (2, 4, 3)
zeros = np.zeros(shape)
print(zeros)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
ones = np.ones(shape)
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
print(np.random.rand())
print(np.random.rand(3))
print(np.random.rand(2, 3))

0.6353788093337025
[0.37337989 0.62615184 0.16498255]
[[0.81407316 0.98417182 0.14381773]
 [0.23336369 0.82402833 0.70667028]]


In [27]:
print(np.random.randn())
print(np.random.randn(2, 3))

0.8045014882788432
[[ 2.22386204  1.19264552 -0.18558074]
 [ 0.7231492   0.36472823 -2.46183186]]


In [28]:
np.random.randint(3, 7, size=(2, 3))

array([[3, 3, 4],
       [3, 4, 6]])

In [29]:
np.random.randint(2, 10, (2, 5))

array([[8, 6, 3, 6, 7],
       [9, 2, 7, 7, 9]])

In [30]:
np.random.randint(2, 10)

5

In [31]:
np.random.randint(1, 100, (5, 2)).reshape(2, 5)

array([[38, 51, 53, 53, 71],
       [52, 47, 91,  8, 12]])

In [32]:
arr = np.arange(0, 12)
print(arr)
print(arr.reshape(3, 4))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# function

In [33]:
ndarr = np.random.randn(5, 5)
ndarr

array([[-1.55910223, -0.12611535, -1.00804821, -0.24456525, -0.84391922],
       [-1.03886917,  0.91176943, -3.19102913,  1.13003053,  0.98056788],
       [-0.77413131,  2.28747724, -0.12879013, -1.3010219 , -0.69437796],
       [-0.75374208, -0.0885121 ,  1.52607648,  1.0720867 , -0.55791539],
       [ 1.20797727, -0.93447082, -0.67366816,  0.19500258, -1.24030513]])

In [34]:
print(ndarr.max())
print(np.max(ndarr))
print(ndarr.argmax())

2.2874772373189307
2.2874772373189307
11


In [35]:
ndarr.flatten()[18]

1.0720866986528845

In [36]:
ndarr.mean()

-0.23390381887915704

In [37]:
np.median(ndarr)

-0.5579153889362783

In [38]:
ndarr.std()

1.1653364958115073

In [39]:
print(ndarr)
print("axis=0: {}".format(ndarr.max(axis=0)))
print("axis=1: {}".format(ndarr.max(axis=1)))

[[-1.55910223 -0.12611535 -1.00804821 -0.24456525 -0.84391922]
 [-1.03886917  0.91176943 -3.19102913  1.13003053  0.98056788]
 [-0.77413131  2.28747724 -0.12879013 -1.3010219  -0.69437796]
 [-0.75374208 -0.0885121   1.52607648  1.0720867  -0.55791539]
 [ 1.20797727 -0.93447082 -0.67366816  0.19500258 -1.24030513]]
axis=0: [1.20797727 2.28747724 1.52607648 1.13003053 0.98056788]
axis=1: [-0.12611535  1.13003053  2.28747724  1.52607648  1.20797727]


In [40]:
# math function
arr = np.linspace(1, 10, 9)
print(np.exp(arr))

[2.71828183e+00 8.37289749e+00 2.57903399e+01 7.94398396e+01
 2.44691932e+02 7.53704213e+02 2.32157241e+03 7.15094647e+03
 2.20264658e+04]


In [41]:
print(np.log(arr))
print(np.log2(arr))
print(np.log10(arr))

[0.         0.7537718  1.178655   1.47590652 1.70474809 1.89085037
 2.04769284 2.18323834 2.30258509]
[0.         1.08746284 1.70043972 2.12928302 2.45943162 2.72792045
 2.95419631 3.14974712 3.32192809]
[0.         0.32735893 0.51188336 0.64097806 0.74036269 0.82118588
 0.8893017  0.94816836 1.        ]


In [42]:
arr = np.linspace(-2, 3, 8)
logarr = np.log(arr)
print(logarr)
print(logarr[0] is None)
print(np.isnan(logarr[0]))

[        nan         nan         nan -1.94591015 -0.15415068  0.45198512
  0.82667857  1.09861229]
False
True


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


In [43]:
print(np.e)
print(np.log(np.e))

2.718281828459045
1.0


In [44]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr.shape)
print(arr)
ex_arr0 = np.expand_dims(arr, axis=0)
ex_arr1 = np.expand_dims(arr, axis=1)
ex_arr2 = np.expand_dims(arr, axis=-1)
print(ex_arr0.shape)
print(ex_arr0)
print(ex_arr1.shape)
print(ex_arr1)
print(ex_arr2.shape)
print(ex_arr2)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(1, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 1, 3)
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
(3, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [45]:
sq_ex_arr = np.squeeze(ex_arr0)
print(sq_ex_arr.shape)
print(sq_ex_arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
flt_arr = arr.flatten()
print(flt_arr.shape)
print(flt_arr)

(9,)
[1 2 3 4 5 6 7 8 9]


In [47]:
arr = np.linspace(1, 100, 100)
np.save('saved_numpy', arr)

In [48]:
loaded_numpy = np.load('saved_numpy.npy')
loaded_numpy

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])