# init numpy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [3]:
python_list = [[1, 1, 1], [2, 2, 2]]
python_list

[[1, 1, 1], [2, 2, 2]]

In [4]:
np_list = np.array([[1, 1, 1], [2, 2, 2]])
np_list

array([[1, 1, 1],
       [2, 2, 2]])

In [11]:
# broadcasting
arr1 = np.array([1, 1, 1])
arr2 = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])

print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 - arr2)
print(arr1 / arr2)

[[11 11 11]
 [21 21 21]
 [31 31 31]]
[[10 10 10]
 [20 20 20]
 [30 30 30]]
[[ -9  -9  -9]
 [-19 -19 -19]
 [-29 -29 -29]]
[[0.1        0.1        0.1       ]
 [0.05       0.05       0.05      ]
 [0.03333333 0.03333333 0.03333333]]


In [12]:
print(arr2)
arr2.shape

[[10 10 10]
 [20 20 20]
 [30 30 30]]


(3, 3)

# index & slice

In [15]:
ndarr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
ndarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
print(ndarr[2][1])
print(ndarr[2, 1])

6
6


In [21]:
print(ndarr[2:, 0])
print(ndarr[:, 1])

[5 7]
[2 4 6 8]


In [24]:
print(ndarr[0:3:2])
print(ndarr[0:3:2, 1])

[[1 2]
 [5 6]]
[2 6]


# gen ndarray